version: {branch}{build}

configuration: Release
before_build:
- ps: >-
    dotnet --info # logs the version of the dotnet client

    Get-ChildItem Env:

environment:
    COVERALLS_REPO_TOKEN:  
       secure: 8HzckJMRXGlu+1IrbwroBW5Uihpw82AgmrBMsbl33hFVC5R4u4PIFoBRiLqMG/4K

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

build_script:
- ps: .\build.ps1

cache:
  - packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - projectA\libs
  - node_modules                        # local npm modules
  - '%APPDATA%\npm-cache'               # npm cache
  - '%USERPROFILE%\.nuget\packages -> **\project.json'  # project.json cache
  - tools -> .\build.cake                              # local tools folder

artifacts:
- path: .\artifacts\*
