version: 0.0.{build}
nuget:
  account_feed: true
configuration: Release
before_build:
- ps: >-
    ./build.ps1

    dotnet --info # logs the version of the dotnet client

    dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
after_build:
- ps: >- 
    dotnet pack  -c Release src\AppVeyorPoc.Library -o .\Artifacts

    dotnet pack -c Release src\AppVeyorPoc.Core -o .\Artifacts
test_script:
- cmd: dotnet test .\tests\AppVeyorPoc.UnirTests\
cache:
  - packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - projectA\libs
  - node_modules                        # local npm modules
  - '%APPDATA%\npm-cache'               # npm cache
  - '%USERPROFILE%\.nuget\packages -> **\project.json'  # project.json cache
  - tools                               # local tools folder
artifacts:
- path: .\Artifacts\*